<a href="https://colab.research.google.com/github/Chrollo09/MNIST-DigitRecognition/blob/main/DigitRecogntion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing required libraries

In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Adding the data set

In [21]:
data = pd.read_csv('sample_data/mnist_train_small.csv')

Creating training data

In [22]:
data = np.array(data)
m, n = data.shape

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.
n_train, m_train = X_train.shape

Shape of our dataset

In [37]:
print(f"The shape of X_train data is:{X_train.shape}")
print(f"The shape of Y_train data is:{Y_train.shape}")

The shape of X_train data is:(784, 18999)
The shape of Y_train data is:(18999,)


Defining our W and B parameters

In [23]:
def init_params():
    W1 = np.random.rand(20, 784) - 0.5
    B1 = np.random.rand(20, 18999) - 0.5
    W2 = np.random.rand(10, 20) - 0.5
    B2 = np.random.rand(10, 18999) - 0.5
    return W1, B1, W2, B2

ReLu function

In [24]:
def ReLu(Z):
    A = np.maximum(0,Z)
    return A

Softmax function

In [25]:
def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A

One Hot Y function

In [26]:
def one_hot(Y):
    one_hot_Y = np.zeros((Y.max() + 1, Y.size))
    one_hot_Y[Y, np.arange(Y.size)] = 1;
    return one_hot_Y

Derivative of relu function

In [27]:
def ReLu_deriv(Z):
    return Z > 0

Forward prop function

In [28]:
def forward_prop(W1, B1, W2, B2, X):
    Z1 = np.dot(W1, X) + B1
    A1 = ReLu(Z1)
    Z2 = np.dot(W2, A1) + B2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

Backward Propagation

In [29]:
def back_prop(Z1, A1, Z2, A2, W2, X, Y):
    m = Y.size
    Y_true = one_hot(Y)
    loss2 = A2 - Y_true
    dW2 = 1 / m * loss2.dot(A1.T)
    dB2 = 1 / m * np.sum(loss2)
    loss1 = W2.T.dot(loss2) * ReLu_deriv(Z1)
    dW1 = 1 / m * loss1.dot(X_train.T)
    dB1 = 1 / m * np.sum(loss1)
    return dW1, dB1, dW2, dB2


Update Parameters

In [30]:
def update_params(W1, B1, W2, B2, dW1, dB1, dW2, dB2, alpha):
    alpha = 0.1
    W1 = W1 - alpha * dW1
    B1 = B1 - alpha * dB1
    W2 = W2 - alpha * dW2
    B2 = B2 - alpha * dB2
    return W1, B1, W2, B2

Predictions

In [31]:
def get_predictions(A2):
    return np.argmax(A2, 0)

Accuracy

In [32]:
def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

Gradient Descent

In [33]:
def grad_descent(X, Y, alpha, iterations):
    W1, B1, W2, B2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, B1, W2, B2, X)
        dW1, dB1, dW2, dB2 = back_prop(Z1, A1, Z2, A2, W2, X, Y)
        W1, B1, W2, B2 = update_params(W1, B1, W2, B2, dW1, dB1, dW2, dB2, alpha)
        if i % 20 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, B1, W2, B2


Calling Gradient Descent

In [35]:
W1, B1, W2, B2 = grad_descent(X_train, Y_train, 0.1, 500)

Iteration:  0
[9 9 9 ... 3 9 6] [9 1 0 ... 2 9 5]
0.10263698089373124
Iteration:  20
[8 1 0 ... 2 8 6] [9 1 0 ... 2 9 5]
0.42939102058003054
Iteration:  40
[8 1 0 ... 2 9 4] [9 1 0 ... 2 9 5]
0.5873993368072004
Iteration:  60
[8 1 0 ... 2 9 5] [9 1 0 ... 2 9 5]
0.6658245170798464
Iteration:  80
[8 1 0 ... 2 9 5] [9 1 0 ... 2 9 5]
0.7089846834043897
Iteration:  100
[8 1 0 ... 2 9 5] [9 1 0 ... 2 9 5]
0.7371440602136955
Iteration:  120
[8 1 0 ... 2 9 5] [9 1 0 ... 2 9 5]
0.755408179377862
Iteration:  140
[9 1 0 ... 2 9 5] [9 1 0 ... 2 9 5]
0.7689878414653403
Iteration:  160
[9 1 0 ... 2 9 5] [9 1 0 ... 2 9 5]
0.7823043318069373
Iteration:  180
[9 1 0 ... 2 9 5] [9 1 0 ... 2 9 5]
0.7946207695141849
Iteration:  200
[9 1 0 ... 2 9 5] [9 1 0 ... 2 9 5]
0.8042002210642666
Iteration:  220
[9 1 0 ... 2 9 5] [9 1 0 ... 2 9 5]
0.8124638138849413
Iteration:  240
[9 1 0 ... 2 9 5] [9 1 0 ... 2 9 5]
0.8187273014369177
Iteration:  260
[9 1 0 ... 2 9 5] [9 1 0 ... 2 9 5]
0.8262013790199484
Iteration: 